In [1]:
import numpy as np

In [2]:
matrix1=np.array([[2,4],[5,7]])
print(matrix1)

[[2 4]
 [5 7]]


In [3]:
matrix1.shape

(2, 2)

In [4]:
matrix2 = np.array([[20,30],[40,50],[60,70]])
print(matrix2)

[[20 30]
 [40 50]
 [60 70]]


In [6]:
matrix2.shape

(3, 2)

Creating matrices with random values

In [9]:
random_matrix = np.random.randint(100,size=(3,3))
print(random_matrix)

[[81 52 58]
 [91 70 93]
 [30 18 89]]


In [10]:
random_matrix = np.random.rand(4,3)
print(random_matrix)

[[0.80985777 0.76183679 0.91367949]
 [0.66395241 0.65414007 0.98626122]
 [0.15991921 0.38351346 0.29305786]
 [0.92959132 0.96550171 0.22907916]]


Matrix containing values as 1

In [12]:
matrix= np.ones((2,3))
print(matrix)

[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
matrix= np.ones((2,3),dtype=int)
print(matrix)

[[1 1 1]
 [1 1 1]]


Null matrix

In [15]:
matrix3 =np.zeros((4,5))
print(matrix3)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Identity matrix

In [17]:
iden_matrix =np.eye(3,3)
print(iden_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
iden_matrix =np.eye(6,6)
print(iden_matrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


Transpose Matrix

In [20]:
rand_matrix = np.random.randint(30,size=(3,4))
transpose_matrix = np.transpose(rand_matrix)
print(rand_matrix)
print(transpose_matrix)


[[ 4  6  5 26]
 [19  5  9 18]
 [ 1 20 28  1]]
[[ 4 19  1]
 [ 6  5 20]
 [ 5  9 28]
 [26 18  1]]
