In [1]:
import numpy as np


Addition of matrices

In [2]:
a=np.array([[2,4],[4,7]])
b=np.array([[4,5],[6,8]])
sum=a+b
print(sum)

[[ 6  9]
 [10 15]]


In [3]:
sum.shape

(2, 2)

In [5]:
a=np.array([[2,4],[4,7],[5,7]])
b=np.array([[4,5],[6,8],[5,9]])
sum=a+b
print(sum)

[[ 6  9]
 [10 15]
 [10 16]]


Subtraction of matrices

In [6]:
c=np.random.randint(20,size=(3,3))
d=np.random.randint(20,size=(3,3))
sub=c-d
print(sub)

[[  2  -4   8]
 [ -9   6   6]
 [ -7 -13  12]]


In [9]:
c=np.random.randint(50,size=(5,3))
d=np.random.randint(40,size=(5,3))
sub=np.subtract(c,d)
print(sub)

[[-10 -21 -27]
 [ 28 -14  26]
 [  3 -15  25]
 [ 48  24  23]
 [ 18  37  -1]]


Multiplying the matrix by scaler

In [10]:
e=np.random.randint(30,size=(4,4))
f=3*e
print(f)

[[12  9 30 75]
 [33 45 54 72]
 [18  3 81 18]
 [24 33 39 36]]


In [12]:
e=np.random.randint(30,size=(4,4))
f=3
prod=np.multiply(e,f)
print(prod)

[[36 33 15 66]
 [ 6 75 18 48]
 [57  0  3  0]
 [12 39 51 36]]


Multiplying the two matrices

In [17]:
g = np.random.randint(5,size=(3,4))
print(g)
f= np.random.randint(5,size=(4,2))
print(f)
prod=np.dot(g,f)
print(prod)

[[1 3 3 3]
 [0 2 0 0]
 [1 4 1 2]]
[[0 3]
 [3 2]
 [1 2]
 [3 4]]
[[21 27]
 [ 6  4]
 [19 21]]


In [15]:
prod.shape

(4, 2)

Element wise multiplication


In [19]:
g = np.random.randint(5,size=(3,4))
print(g)
f= np.random.randint(5,size=(4,2))
print(f)
prod=np.multiply(g,f)
print(prod)

[[3 3 4 0]
 [2 1 4 1]
 [4 1 4 4]]
[[4 2]
 [3 4]
 [1 2]
 [0 4]]


ValueError: ignored

In [20]:
g = np.random.randint(5,size=(3,4))
print(g)
f= np.random.randint(5,size=(3,4))
print(f)
prod=np.multiply(g,f)
print(prod)

[[4 4 1 1]
 [3 4 2 3]
 [0 2 3 4]]
[[2 3 0 2]
 [2 1 4 3]
 [1 4 3 0]]
[[ 8 12  0  2]
 [ 6  4  8  9]
 [ 0  8  9  0]]
